<?php

/**
 * Implements hook_form_FORM_ID_alter().
 * @param  array  &$form       Nested array of form elements that comprise the form.
 * @param  array  &$form_state A keyed array containing the current state of the form.
 * @param  string $form_id     String representing the name of the form itself.
 * @return array               the altered form by reference
 */
function language_menu_item_form_menu_edit_item_alter(&$form, &$form_state, $form_id) {

  $default = '';
  $item = $form['original_item']['#value'];
  if (isset($item['options']['language'])) {
    $default = $item['options']['language'];
  }
  $options = array('' => t('Language neutral'));
  $language_list = language_list();
  foreach ($language_list as $value) {
    $options[$value->langcode] = $value->name;
  }

  $form['language_select'] = array(
    '#type' => 'select',
    '#title' => t('Language'),
    '#default_value' => empty($default) ? '' : $default->langcode,
    '#options' => $options,
  );
  $form['#submit'][] = 'language_menu_item_form_menu_edit_item_submit';
}


/**
 * Implements form_submit().
 * @param  array  &$form       Nested array of form elements that comprise the form.
 * @param  array  &$form_state A keyed array containing the current state of the form.
 */
function language_menu_item_form_menu_edit_item_submit($form, $form_state) {
  $values = $form_state['values'];

  $item = $values['original_item'];
  $language = $values['language_select'];

  if (!empty($language)) {
    $language_list = language_list('enabled');
    if (isset($language_list[$language])) {
      $item['options']['language'] = $language_list[$language];
    }
  }
  else {
    // remove language context if exists
    if (isset($item['options']['language'])) {
      unset($item['options']['language']);
    }
    if (isset($item['localized_options']['language'])) {
      unset($item['localized_options']['language']);
    }
  }
  menu_link_save($item);
}
